# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Listenn' do

pod 'Alamofire', '~> 3.3'

end

target 'ListennTests' do

end

target 'ListennUITests' do

end

